### ISSUE TITLE
[Mechanics] - inteference in the assembly

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#5]
There are clipping parts in the assembly that should be looked at. I suspect there is additional interference around the circled areas on the picture. Usually, there should be no interference.
![image](https://user-images.githubusercontent.com/5435954/134521170-5d7534a6-8c86-4935-99e3-8e7c3f0419a8.png)

**Comment by erkiveevali** [comment]
Since I changed the components and joints due to other issues then those interference problems should be resolved as well. Fusion  still shows some interference in the assembly, but I'm not entirely sure why.

**Comment by Akustav** [comment]
I suggest checking how these 4 corners are cut in the actual model:

![image](https://user-images.githubusercontent.com/5435954/135150769-8bcd5a66-2af4-40e9-a338-0b46f6c35510.png)


There might be some radiuses that are not accounted for in the design but are there due to milling

**Comment by erkiveevali** [comment]
The top ones are fine, since the sides of the ramps arent touching the plate and the corners of the hole in the plate aren't sharp 90degree angles.
On the bottom plate however, the angles do have a small radius that isnt present on the model. I'd say I just file the corners on the bottom plate a bit, to make the ramps fit snugly right against the bottom plate. Thats because I'd like the ramps to be supported by the plate like that.

**Comment by Akustav** [comment]
This issue is then OK. You can continue with the CAM
