### ISSUE TITLE
[Mechanics] - potential recreation of issue with thrower

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#90]
If I remember correctly there is an issue with your current thrower that does not center the ball to well. When the ball rolls into the robot depending on which side it hits first, the ball gets grabbed and thrown differently. The areas in question:
![image](https://user-images.githubusercontent.com/5435954/145105121-5bfd00ea-f46a-4f6f-b6cd-f632eaf1a9eb.png)

I would discuss it with your programmers. One solution would be to move the thrower sidewalls closer in the front or move the motor back a little so the ball has some time to calm down before it is pulled into the thrower motor.

I think the thrower can be moved at least 2 cm inwards or even more, when you shorten the small ramp height.

**Comment by erkiveevali** [comment]
Discussed the issue with Uku and we think that the issue on the old robot is mostly caused by the fact that the thrower sidewalls (especially one of them) dont fit the bottom plate that well. The cause of that problem is the fact we needed to modify the parts after milling to get them to fit at all. The whole test thrower moved to the front and created those corners that interfere with the ball. Although I cut the interfering corners, the current solution isnt ideal at the moment. As long as the new parts fit together like do in the model, that shouldnt be as big of an issue as it is now.

Moving the thrower inwards could yield better results in giving the ball time to calm down but it also means the robot has to move "blindly" forward more for the ball to reach the motor. So that could cause other problems. 

Also moving the thrower inwards as much as 2cm will take but most of the free space behind the thrower (which was initially meant for motor wiring etc to fit into) leaving very little room inside the robot.

So I am not against moving the thrower inwards but I am not sure how much better results that would give overall

**Comment by Akustav** [comment]
Yeah, I agree that it is a tradeoff and your decision in the end. Some things to consider:

As for moving the thrower inside, I also took into account that the ramp can be slimmed down and moved without much effort. Size of cabling on the motors is quite minimal, in my opinion. As for the blindly part the robot aims towards the basket at all times so it should not affect accuracy when the visual on the ball is lost. Overall I would try to achieve as robust a physical design as possible to allow for maximum accuracy. Every missed shot costs a lot of time and gives opponents an additional oppurtunity.

**Comment by erkiveevali** [comment]
![image](https://user-images.githubusercontent.com/79630265/145238741-3da13f3b-e44f-49f6-8859-5d8d5e9dbdd4.png)
Was able to move the motor inside 11mm without redoing the ramps or thrower sides. Hopefully its better that way.

**Comment by Akustav** [comment]
I would add something like this as well:

![image](https://user-images.githubusercontent.com/5435954/145266394-357a7f5a-674e-48fd-b125-9ddd859c9e35.png)

It strengthens the ramp again and also supports it by resting the piece on the top and bottom plate

**Comment by erkiveevali** [comment]
Reinforced the ramps as described on the picture
